apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURReQpNVFUwTVRWYUZ3MDBNakE0TURReU1UVTBNVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDOHVsZXFGK2FKZlZsUjV6VDJFVkF4a0RDY3J3d204aFpNMFFGWXg0K2xoNVJWL2tSRAorNDFYNFNWdXV5ai9HdVVkZzZHVlZqL2oyclJUaHFnTVlIbnNiNlVXOTBRWklXbldjeEdtUlY3ZG0vSmNzclBaCnZZUmgya1RzeUtDU2MwS2tKeWxET2JHZGRIVnhINld3dGc2cXgwbTdIRmdCRG9qVDNHR0Y2WmdzQ3Rnd0JWZjQKbnZFRjdxVmZnZE54NTdjc0RlcmpBeXROd05IQ0lMNHNKeHhWa3VKMTc2MmRyNlZ5ak1rbEdOZG52aHlMa0cxNwo5bEdDZTVLTHlEUnhrbVIybWJ4UVhHYmFtMmJ4OXZSMnRCRTUvb2gwNm9HUVY0RmVUcmhSN2xNS3FDMUswSmk2CkQ3bVd6YlVmZDFrN1ViTUJGczVsckNWdVlVNkFaMGhGbGVZL0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNoeDF6emZqSndJYittNS9zRQpFWVNjY2hBWjRUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJQXBIM2NxMlRFbmxVVmFDYW9YRW5UT2J6RWxzCmowSi96bWY2Z2FkcUczK1NpNjRFMWJZbExVL2hHQnQweFRSMjRPbW5tK3pWSnJUREp3ZFVWOTBRYk1kb2FiQXQKNHBMMmdpdjdhUDRqT1Z4UCtTR3FMMFcxR0wxbU0xUW9FOG8vMHZnd2k5QlNLWXpzVWpXemduSW9YdEd6VmhOcgovNko5YW9IT3JMVmNIcE9IdmpzcTFoVHhkYVhlbEZYQlpoZUtmbGtSZld3citEblRBMW1kMEcwbGQ0bW5DYVZwCk85MFFiZStJR2Y2eS9qS3ZzejA0bUNldkFNT0lhVHg4U0hlV2piSDlqV0g0bWEzei96ZlFXa2RxMWhZT1pYYXMKNXQ3dysycmlmZDNaT1hERGRINjgwbkJvM0tKdUxWd2JYUTI3bEtzOFhWajZSNWg3UFFlR0tINXQ4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c28520dc-b77e-4054-9d71-36852a26e008.k8s.ondigitalocean.com
  name: do-nyc1-kube-news-ocean
contexts:
- context:
    cluster: do-nyc1-kube-news-ocean
    user: do-nyc1-kube-news-ocean-admin
  name: do-nyc1-kube-news-ocean
current-context: do-nyc1-kube-news-ocean
users:
- name: do-nyc1-kube-news-ocean-admin
  user:
    token: dop_v1_70277daed16f6883bc29b6717e2512d8e47c0861d4103c9fdbe9f750bad3b75e
